//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISBD_project.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Shared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ISBD_project.Resources.Shared", typeof(Shared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LangCourser is a thriving student web portal project for the creating, realization and evaluation of language courses!.
        /// </summary>
        public static string AdditionalInfo {
            get {
                return ResourceManager.GetString("AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project was led by two students:.
        /// </summary>
        public static string AdditionalInfov2 {
            get {
                return ResourceManager.GetString("AdditionalInfov2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Artur Achmatow - 220951.
        /// </summary>
        public static string AdditionalInfov3 {
            get {
                return ResourceManager.GetString("AdditionalInfov3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Daniel Sikora - 228936.
        /// </summary>
        public static string AdditionalInfov4 {
            get {
                return ResourceManager.GetString("AdditionalInfov4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project is still in the implementation phase, however, it has many forward-looking perspectives..
        /// </summary>
        public static string AdditionalInfov5 {
            get {
                return ResourceManager.GetString("AdditionalInfov5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avarage.
        /// </summary>
        public static string AvarageScore {
            get {
                return ResourceManager.GetString("AvarageScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us with:.
        /// </summary>
        public static string Contactuswith {
            get {
                return ResourceManager.GetString("Contactuswith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Name.
        /// </summary>
        public static string CourseName {
            get {
                return ResourceManager.GetString("CourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string Courses {
            get {
                return ResourceManager.GetString("Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date is required.
        /// </summary>
        public static string DateRequired {
            get {
                return ResourceManager.GetString("DateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developers:.
        /// </summary>
        public static string Devs {
            get {
                return ResourceManager.GetString("Devs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello .
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEARN ENGLISH, FRENCH, SPANISH, GERMAN, ITALIAN, CHINESE, POLISH!.
        /// </summary>
        public static string Homelabelv1 {
            get {
                return ResourceManager.GetString("Homelabelv1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These and many other languages, you can only learn with us !!!.
        /// </summary>
        public static string Homelabelv2 {
            get {
                return ResourceManager.GetString("Homelabelv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language courses.
        /// </summary>
        public static string LangCourses {
            get {
                return ResourceManager.GetString("LangCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecturer.
        /// </summary>
        public static string Lecturer {
            get {
                return ResourceManager.GetString("Lecturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered an incorrect login and/or password.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Courses.
        /// </summary>
        public static string MyCourses {
            get {
                return ResourceManager.GetString("MyCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses You Lead:.
        /// </summary>
        public static string MyCourses_I_Lead {
            get {
                return ResourceManager.GetString("MyCourses_I_Lead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses You Participate:.
        /// </summary>
        public static string MyCourses_I_Participate {
            get {
                return ResourceManager.GetString("MyCourses_I_Participate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a brand new account.
        /// </summary>
        public static string NewAccount {
            get {
                return ResourceManager.GetString("NewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears you don&apos;t have access to this site :(.
        /// </summary>
        public static string NoAccess {
            get {
                return ResourceManager.GetString("NoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        public static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Passwords are not matching.
        /// </summary>
        public static string PasswordsNotMatching {
            get {
                return ResourceManager.GetString("PasswordsNotMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        public static string Polish {
            get {
                return ResourceManager.GetString("Polish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new account has been successfully registered!.
        /// </summary>
        public static string Registered {
            get {
                return ResourceManager.GetString("Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Password.
        /// </summary>
        public static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score course.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more.
        /// </summary>
        public static string Seemore {
            get {
                return ResourceManager.GetString("Seemore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You correctly signed to the course!.
        /// </summary>
        public static string SignToCorrect {
            get {
                return ResourceManager.GetString("SignToCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were already signed to this course!.
        /// </summary>
        public static string SignToError {
            get {
                return ResourceManager.GetString("SignToError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hota&apos;la Salsa Espaniola.
        /// </summary>
        public static string Topic1 {
            get {
                return ResourceManager.GetString("Topic1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready for the hottest salse in the universe?.
        /// </summary>
        public static string Topic1desc1 {
            get {
                return ResourceManager.GetString("Topic1desc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salsa, Tequila and many others only on our Spanish course..
        /// </summary>
        public static string Topic1desc2 {
            get {
                return ResourceManager.GetString("Topic1desc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s light a Spaniard in you..
        /// </summary>
        public static string Topic1desc3 {
            get {
                return ResourceManager.GetString("Topic1desc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As the leader of our wonderful MaryJJ (Marianna Johhanof)!.
        /// </summary>
        public static string Topic1desc4 {
            get {
                return ResourceManager.GetString("Topic1desc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zhōngwén kèchéng.
        /// </summary>
        public static string Topic2 {
            get {
                return ResourceManager.GetString("Topic2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relax, if you do not understand it, you&apos;re not alone!.
        /// </summary>
        public static string Topic2desc1 {
            get {
                return ResourceManager.GetString("Topic2desc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s Chinese! Would you like to know his mysteries, immeasurable like the wall?.
        /// </summary>
        public static string Topic2desc2 {
            get {
                return ResourceManager.GetString("Topic2desc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This course is just for you!.
        /// </summary>
        public static string Topic2desc3 {
            get {
                return ResourceManager.GetString("Topic2desc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obviously leading Zhang is waiting (Zhang Ziyi)!.
        /// </summary>
        public static string Topic2desc4 {
            get {
                return ResourceManager.GetString("Topic2desc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schweinehund.
        /// </summary>
        public static string Topic3 {
            get {
                return ResourceManager.GetString("Topic3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you ever wanted to get to know German?.
        /// </summary>
        public static string Topic3desc1 {
            get {
                return ResourceManager.GetString("Topic3desc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Germany, these are our neighbors! I think it&apos;s worth being able to get along with them!.
        /// </summary>
        public static string Topic3desc2 {
            get {
                return ResourceManager.GetString("Topic3desc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This opportunity stands around the corner!.
        /// </summary>
        public static string Topic3desc3 {
            get {
                return ResourceManager.GetString("Topic3desc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helga cannot wait (Helga Smirnoff)!.
        /// </summary>
        public static string Topic3desc4 {
            get {
                return ResourceManager.GetString("Topic3desc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User affiliation.
        /// </summary>
        public static string UserAffiliation {
            get {
                return ResourceManager.GetString("UserAffiliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Language.
        /// </summary>
        public static string WebLanguage {
            get {
                return ResourceManager.GetString("WebLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account with given email address already exists.
        /// </summary>
        public static string WrongEmail {
            get {
                return ResourceManager.GetString("WrongEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account with given login already exists.
        /// </summary>
        public static string WrongLogin {
            get {
                return ResourceManager.GetString("WrongLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string YouSure {
            get {
                return ResourceManager.GetString("YouSure", resourceCulture);
            }
        }
    }
}
